# Generated by Django 5.0.7 on 2025-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Your company name', max_length=200)),
                ('company_email', models.EmailField(help_text='Main business email', max_length=254)),
                ('company_phone', models.CharField(blank=True, help_text='Main phone number', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp business number', max_length=20)),
                ('company_address', models.TextField(blank=True, help_text='Full business address')),
                ('opening_hours', models.TextField(blank=True, help_text='Business opening hours (e.g., Mon-Fri: 9:00-17:00)')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly service rate', max_digits=8, null=True)),
                ('currency', models.CharField(default='EUR', help_text='Currency for pricing', max_length=10)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn company page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('domain_auto_registration', models.BooleanField(default=False, help_text='Enable automatic domain registration')),
                ('hosting_auto_provision', models.BooleanField(default=False, help_text='Enable automatic hosting setup')),
                ('search_engine_submission', models.BooleanField(default=True, help_text='Automatically submit to search engines')),
                ('seo_plan', models.CharField(choices=[('basic', 'Basic SEO (Free)'), ('premium', 'Premium SEO')], default='basic', max_length=20)),
                ('enabled_languages', models.JSONField(default=list, help_text='List of enabled languages for this site')),
                ('default_language', models.CharField(default='en', help_text='Default site language', max_length=10)),
                ('watermark_enabled', models.BooleanField(default=False, help_text='Add watermark to uploaded images')),
                ('watermark_text', models.CharField(blank=True, help_text='Watermark text (company name)', max_length=100)),
                ('watermark_opacity', models.IntegerField(default=50, help_text='Watermark opacity (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
