# Generated by Django 5.0.7 on 2025-10-07 03:44

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_nl', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('title_pt', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Main page content')),
                ('content_en', ckeditor.fields.RichTextField(blank=True)),
                ('content_nl', ckeditor.fields.RichTextField(blank=True)),
                ('content_de', ckeditor.fields.RichTextField(blank=True)),
                ('content_fr', ckeditor.fields.RichTextField(blank=True)),
                ('content_es', ckeditor.fields.RichTextField(blank=True)),
                ('content_pt', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('is_homepage', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section identifier', max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(blank=True)),
                ('content_nl', ckeditor.fields.RichTextField(blank=True)),
                ('content_de', ckeditor.fields.RichTextField(blank=True)),
                ('content_fr', ckeditor.fields.RichTextField(blank=True)),
                ('content_es', ckeditor.fields.RichTextField(blank=True)),
                ('content_pt', ckeditor.fields.RichTextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'name')},
            },
        ),
    ]
