# Generated by Django 5.0.7 on 2025-10-07 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('faq', 'FAQ'), ('service', 'Service Information'), ('pricing', 'Pricing Details'), ('process', 'Process Explanation'), ('feature', 'Feature Description'), ('policy', 'Policy Information')], max_length=20)),
                ('content', models.TextField(help_text='Knowledge content for AI training')),
                ('content_en', models.TextField(blank=True)),
                ('content_nl', models.TextField(blank=True)),
                ('content_de', models.TextField(blank=True)),
                ('content_fr', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('content_pt', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list, help_text='Keywords that trigger this content')),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers = higher priority')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_company', models.CharField(blank=True, max_length=100)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('session_type', models.CharField(choices=[('anonymous', 'Anonymous Visitor'), ('lead', 'Potential Customer'), ('customer', 'Existing Customer'), ('support', 'Support Request')], default='anonymous', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('referrer_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('detected_industry', models.CharField(blank=True, max_length=50)),
                ('budget_signals', models.JSONField(blank=True, default=dict)),
                ('lead_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ai_response', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('corrected_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'AI Assistant'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('ai_model', models.CharField(blank=True, max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0.0)),
                ('intent_detected', models.CharField(blank=True, max_length=50)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('entities_extracted', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
