# Generated by Django 5.0.7 on 2025-10-07 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('business', 'General Business'), ('construction', 'Construction & Building'), ('technology', 'Technology & IT'), ('restaurant', 'Restaurant & Food'), ('health', 'Healthcare & Wellness'), ('creative', 'Creative & Design'), ('ecommerce', 'E-commerce'), ('portfolio', 'Portfolio & Personal')], max_length=50)),
                ('description', models.TextField()),
                ('html_template', models.TextField()),
                ('css_template', models.TextField()),
                ('js_template', models.TextField(blank=True)),
                ('supports_one_page', models.BooleanField(default=True)),
                ('supports_multi_page', models.BooleanField(default=True)),
                ('color_schemes', models.JSONField(blank=True, default=list)),
                ('font_options', models.JSONField(blank=True, default=list)),
                ('preview_image', models.URLField(blank=True)),
                ('thumbnail_image', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website Template',
                'verbose_name_plural': 'Website Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('page_type', models.CharField(choices=[('one_page', 'One Page Website'), ('multi_page', 'Multi-Page Website'), ('landing_page', 'Landing Page'), ('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce')], default='one_page', max_length=20)),
                ('business_description', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('template_id', models.CharField(blank=True, max_length=50)),
                ('color_scheme', models.CharField(default='professional', max_length=50)),
                ('font_style', models.CharField(default='modern', max_length=50)),
                ('content_tone', models.CharField(default='professional', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('content_review', 'Content Review'), ('design_review', 'Design Review'), ('completed', 'Completed'), ('published', 'Published'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('assistant_conversation_id', models.CharField(blank=True, max_length=100)),
                ('generated_content', models.JSONField(blank=True, default=dict)),
                ('final_html', models.TextField(blank=True)),
                ('final_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Project',
                'verbose_name_plural': 'Website Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteBuilderConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('welcome', 'Welcome & Introduction'), ('business_name', 'Business Name Collection'), ('industry_selection', 'Industry Selection'), ('services_selection', 'Services Selection'), ('business_details', 'Business Details Collection'), ('template_selection', 'Template Selection'), ('content_generation', 'Content Generation'), ('content_review', 'Content Review & Editing'), ('final_review', 'Final Review'), ('completion', 'Project Completion')], default='welcome', max_length=30)),
                ('conversation_data', models.JSONField(blank=True, default=dict)),
                ('step_progress', models.JSONField(blank=True, default=dict)),
                ('total_messages', models.IntegerField(default=0)),
                ('assistant_personality', models.CharField(default='helpful', max_length=50)),
                ('user_expertise_level', models.CharField(default='beginner', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation', to='website_builder.websiteproject')),
            ],
            options={
                'verbose_name': 'Website Builder Conversation',
                'verbose_name_plural': 'Website Builder Conversations',
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('detailed_description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='website_builder.websiteproject')),
            ],
            options={
                'verbose_name': 'Business Service',
                'verbose_name_plural': 'Business Services',
                'ordering': ['display_order', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('common_services', models.JSONField(blank=True, default=list)),
                ('business_description_template', models.TextField(blank=True)),
                ('services_intro_template', models.TextField(blank=True)),
                ('about_us_template', models.TextField(blank=True)),
                ('common_keywords', models.JSONField(blank=True, default=list)),
                ('target_audience_suggestions', models.JSONField(blank=True, default=list)),
                ('recommended_colors', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_templates', models.ManyToManyField(blank=True, to='website_builder.websitetemplate')),
            ],
            options={
                'verbose_name': 'Industry Template',
                'verbose_name_plural': 'Industry Templates',
                'ordering': ['display_name'],
            },
        ),
    ]
