# Generated by Django 5.0.7 on 2025-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='final_js',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='template_used',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
