# Generated by Django 5.0.7 on 2025-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_builder', '0002_websiteproject_final_js_websiteproject_template_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='website_type',
            field=models.CharField(choices=[('one_page', 'One Page Website'), ('multi_page', 'Multi-Page Website'), ('landing_page', 'Landing Page'), ('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce')], default='one_page', max_length=20),
        ),
    ]
