# Generated by Django 5.0.7 on 2025-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_builder', '0003_websiteproject_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='opening_times',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
